# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/unknownpgr/embedded

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/unknownpgr/embedded

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/unknownpgr/embedded/CMakeFiles /home/unknownpgr/embedded/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/unknownpgr/embedded/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named recognize

# Build rule for target.
recognize: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 recognize
.PHONY : recognize

# fast build rule for target.
recognize/fast:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/build
.PHONY : recognize/fast

#=============================================================================
# Target rules for targets named ctrlboard

# Build rule for target.
ctrlboard: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ctrlboard
.PHONY : ctrlboard

# fast build rule for target.
ctrlboard/fast:
	$(MAKE) -f CMakeFiles/ctrlboard.dir/build.make CMakeFiles/ctrlboard.dir/build
.PHONY : ctrlboard/fast

src/recognize/display-kms.o: src/recognize/display-kms.c.o

.PHONY : src/recognize/display-kms.o

# target to build an object file
src/recognize/display-kms.c.o:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/recognize/display-kms.c.o
.PHONY : src/recognize/display-kms.c.o

src/recognize/display-kms.i: src/recognize/display-kms.c.i

.PHONY : src/recognize/display-kms.i

# target to preprocess a source file
src/recognize/display-kms.c.i:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/recognize/display-kms.c.i
.PHONY : src/recognize/display-kms.c.i

src/recognize/display-kms.s: src/recognize/display-kms.c.s

.PHONY : src/recognize/display-kms.s

# target to generate assembly for a file
src/recognize/display-kms.c.s:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/recognize/display-kms.c.s
.PHONY : src/recognize/display-kms.c.s

src/recognize/recognize-lib.o: src/recognize/recognize-lib.c.o

.PHONY : src/recognize/recognize-lib.o

# target to build an object file
src/recognize/recognize-lib.c.o:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/recognize/recognize-lib.c.o
.PHONY : src/recognize/recognize-lib.c.o

src/recognize/recognize-lib.i: src/recognize/recognize-lib.c.i

.PHONY : src/recognize/recognize-lib.i

# target to preprocess a source file
src/recognize/recognize-lib.c.i:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/recognize/recognize-lib.c.i
.PHONY : src/recognize/recognize-lib.c.i

src/recognize/recognize-lib.s: src/recognize/recognize-lib.c.s

.PHONY : src/recognize/recognize-lib.s

# target to generate assembly for a file
src/recognize/recognize-lib.c.s:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/recognize/recognize-lib.c.s
.PHONY : src/recognize/recognize-lib.c.s

src/recognize/recognize-update.o: src/recognize/recognize-update.c.o

.PHONY : src/recognize/recognize-update.o

# target to build an object file
src/recognize/recognize-update.c.o:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/recognize/recognize-update.c.o
.PHONY : src/recognize/recognize-update.c.o

src/recognize/recognize-update.i: src/recognize/recognize-update.c.i

.PHONY : src/recognize/recognize-update.i

# target to preprocess a source file
src/recognize/recognize-update.c.i:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/recognize/recognize-update.c.i
.PHONY : src/recognize/recognize-update.c.i

src/recognize/recognize-update.s: src/recognize/recognize-update.c.s

.PHONY : src/recognize/recognize-update.s

# target to generate assembly for a file
src/recognize/recognize-update.c.s:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/recognize/recognize-update.c.s
.PHONY : src/recognize/recognize-update.c.s

src/recognize/recognize.o: src/recognize/recognize.c.o

.PHONY : src/recognize/recognize.o

# target to build an object file
src/recognize/recognize.c.o:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/recognize/recognize.c.o
.PHONY : src/recognize/recognize.c.o

src/recognize/recognize.i: src/recognize/recognize.c.i

.PHONY : src/recognize/recognize.i

# target to preprocess a source file
src/recognize/recognize.c.i:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/recognize/recognize.c.i
.PHONY : src/recognize/recognize.c.i

src/recognize/recognize.s: src/recognize/recognize.c.s

.PHONY : src/recognize/recognize.s

# target to generate assembly for a file
src/recognize/recognize.c.s:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/recognize/recognize.c.s
.PHONY : src/recognize/recognize.c.s

src/recognize/v4l2.o: src/recognize/v4l2.c.o

.PHONY : src/recognize/v4l2.o

# target to build an object file
src/recognize/v4l2.c.o:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/recognize/v4l2.c.o
.PHONY : src/recognize/v4l2.c.o

src/recognize/v4l2.i: src/recognize/v4l2.c.i

.PHONY : src/recognize/v4l2.i

# target to preprocess a source file
src/recognize/v4l2.c.i:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/recognize/v4l2.c.i
.PHONY : src/recognize/v4l2.c.i

src/recognize/v4l2.s: src/recognize/v4l2.c.s

.PHONY : src/recognize/v4l2.s

# target to generate assembly for a file
src/recognize/v4l2.c.s:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/recognize/v4l2.c.s
.PHONY : src/recognize/v4l2.c.s

src/recognize/vpe-common.o: src/recognize/vpe-common.c.o

.PHONY : src/recognize/vpe-common.o

# target to build an object file
src/recognize/vpe-common.c.o:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/recognize/vpe-common.c.o
.PHONY : src/recognize/vpe-common.c.o

src/recognize/vpe-common.i: src/recognize/vpe-common.c.i

.PHONY : src/recognize/vpe-common.i

# target to preprocess a source file
src/recognize/vpe-common.c.i:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/recognize/vpe-common.c.i
.PHONY : src/recognize/vpe-common.c.i

src/recognize/vpe-common.s: src/recognize/vpe-common.c.s

.PHONY : src/recognize/vpe-common.s

# target to generate assembly for a file
src/recognize/vpe-common.c.s:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/recognize/vpe-common.c.s
.PHONY : src/recognize/vpe-common.c.s

src/shared/ctrlboard-lib.o: src/shared/ctrlboard-lib.c.o

.PHONY : src/shared/ctrlboard-lib.o

# target to build an object file
src/shared/ctrlboard-lib.c.o:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/shared/ctrlboard-lib.c.o
	$(MAKE) -f CMakeFiles/ctrlboard.dir/build.make CMakeFiles/ctrlboard.dir/src/shared/ctrlboard-lib.c.o
.PHONY : src/shared/ctrlboard-lib.c.o

src/shared/ctrlboard-lib.i: src/shared/ctrlboard-lib.c.i

.PHONY : src/shared/ctrlboard-lib.i

# target to preprocess a source file
src/shared/ctrlboard-lib.c.i:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/shared/ctrlboard-lib.c.i
	$(MAKE) -f CMakeFiles/ctrlboard.dir/build.make CMakeFiles/ctrlboard.dir/src/shared/ctrlboard-lib.c.i
.PHONY : src/shared/ctrlboard-lib.c.i

src/shared/ctrlboard-lib.s: src/shared/ctrlboard-lib.c.s

.PHONY : src/shared/ctrlboard-lib.s

# target to generate assembly for a file
src/shared/ctrlboard-lib.c.s:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/shared/ctrlboard-lib.c.s
	$(MAKE) -f CMakeFiles/ctrlboard.dir/build.make CMakeFiles/ctrlboard.dir/src/shared/ctrlboard-lib.c.s
.PHONY : src/shared/ctrlboard-lib.c.s

src/shared/ctrlboard.o: src/shared/ctrlboard.c.o

.PHONY : src/shared/ctrlboard.o

# target to build an object file
src/shared/ctrlboard.c.o:
	$(MAKE) -f CMakeFiles/ctrlboard.dir/build.make CMakeFiles/ctrlboard.dir/src/shared/ctrlboard.c.o
.PHONY : src/shared/ctrlboard.c.o

src/shared/ctrlboard.i: src/shared/ctrlboard.c.i

.PHONY : src/shared/ctrlboard.i

# target to preprocess a source file
src/shared/ctrlboard.c.i:
	$(MAKE) -f CMakeFiles/ctrlboard.dir/build.make CMakeFiles/ctrlboard.dir/src/shared/ctrlboard.c.i
.PHONY : src/shared/ctrlboard.c.i

src/shared/ctrlboard.s: src/shared/ctrlboard.c.s

.PHONY : src/shared/ctrlboard.s

# target to generate assembly for a file
src/shared/ctrlboard.c.s:
	$(MAKE) -f CMakeFiles/ctrlboard.dir/build.make CMakeFiles/ctrlboard.dir/src/shared/ctrlboard.c.s
.PHONY : src/shared/ctrlboard.c.s

src/shared/util.o: src/shared/util.c.o

.PHONY : src/shared/util.o

# target to build an object file
src/shared/util.c.o:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/shared/util.c.o
	$(MAKE) -f CMakeFiles/ctrlboard.dir/build.make CMakeFiles/ctrlboard.dir/src/shared/util.c.o
.PHONY : src/shared/util.c.o

src/shared/util.i: src/shared/util.c.i

.PHONY : src/shared/util.i

# target to preprocess a source file
src/shared/util.c.i:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/shared/util.c.i
	$(MAKE) -f CMakeFiles/ctrlboard.dir/build.make CMakeFiles/ctrlboard.dir/src/shared/util.c.i
.PHONY : src/shared/util.c.i

src/shared/util.s: src/shared/util.c.s

.PHONY : src/shared/util.s

# target to generate assembly for a file
src/shared/util.c.s:
	$(MAKE) -f CMakeFiles/recognize.dir/build.make CMakeFiles/recognize.dir/src/shared/util.c.s
	$(MAKE) -f CMakeFiles/ctrlboard.dir/build.make CMakeFiles/ctrlboard.dir/src/shared/util.c.s
.PHONY : src/shared/util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... recognize"
	@echo "... ctrlboard"
	@echo "... src/recognize/display-kms.o"
	@echo "... src/recognize/display-kms.i"
	@echo "... src/recognize/display-kms.s"
	@echo "... src/recognize/recognize-lib.o"
	@echo "... src/recognize/recognize-lib.i"
	@echo "... src/recognize/recognize-lib.s"
	@echo "... src/recognize/recognize-update.o"
	@echo "... src/recognize/recognize-update.i"
	@echo "... src/recognize/recognize-update.s"
	@echo "... src/recognize/recognize.o"
	@echo "... src/recognize/recognize.i"
	@echo "... src/recognize/recognize.s"
	@echo "... src/recognize/v4l2.o"
	@echo "... src/recognize/v4l2.i"
	@echo "... src/recognize/v4l2.s"
	@echo "... src/recognize/vpe-common.o"
	@echo "... src/recognize/vpe-common.i"
	@echo "... src/recognize/vpe-common.s"
	@echo "... src/shared/ctrlboard-lib.o"
	@echo "... src/shared/ctrlboard-lib.i"
	@echo "... src/shared/ctrlboard-lib.s"
	@echo "... src/shared/ctrlboard.o"
	@echo "... src/shared/ctrlboard.i"
	@echo "... src/shared/ctrlboard.s"
	@echo "... src/shared/util.o"
	@echo "... src/shared/util.i"
	@echo "... src/shared/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

